version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root -proot
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    # volumes:
    #   - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8080:80
    depends_on:
      - mysql
  migration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: migration
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy

    command: goose -dir /migrations mysql "user:password@tcp(mysql:3306)/db" up
    volumes:
      - ./db/migrations:/migrations
